
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="./asset/css/styles_gallery.css">
    <link rel="stylesheet" href="./asset/css/styles_home.css">
    <link rel="stylesheet" href="./asset/css/styles_article.css">
    <link rel="stylesheet" href="./asset/css/styles_search.css">
    <link rel="stylesheet" href="./asset/css/styles_log.css">

    <link rel="stylesheet" href="./asset/css/styles_follow.css">
    <link rel="stylesheet" href="./asset/css/styles_admin.css">
    <link rel="stylesheet" href="./asset/css/styles_pageusers.css">



</head>

<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg bg-body-secondary fixed-top" >
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" style="justify-content:space-between;">

                <form class="d-flex" role="search">
                    <input name="page" value="search" type="hidden"> 
                    <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

                <?php if (isset($_SESSION['pseudo'])) { ?>
                    <div class="navUser">
                        <a href="#"> <img src="https://static.vecteezy.com/ti/vecteur-libre/p3/6086198-icone-de-notification-pour-le-web-vectoriel.jpg" alt="" class="imgUser"></a>

                        <a href="index.php?page=articlelist"> <img src="<?= $_SESSION['photo']; ?>" alt="" class="imgUser"></a>

                    </div>
                <?php } else { ?>
                    <a href="index.php?page=log" class="m-2 link-connect">Connexion / Inscription</a>

                <?php } ?>


            </div>
        </div>
    </nav>
    <main>
        <div class="homeContent">
            <div class="options">
                <div class="underOption">
                    <div class="navSet">
                        <ul><?php if (isset($_SESSION['pseudo'])) { ?>
                                <a href="?page=userpage&id=<?= $_SESSION['id']; ?>">
                                    <li>
                                        <img src="<?= $_SESSION['photo']; ?>" alt="" class="iconNav">
                                        <?= $_SESSION['pseudo']; ?>
                                    </li>
                                </a>
                            <?php } ?>
                            <a href="index.php?page=home">
                                <li><img src="./asset/img/iconHome.png" alt="" class="iconNav">Home</li>
                            </a>
                            <?php if (isset($_SESSION['pseudo'])) { ?>
                                <a href="index.php?page=follow">
                                    <li><img src="./asset/img/iconFollow.png" alt="" class="iconNav">Pages Follow</li>
                                </a>
                                <a href="index.php?page=articlelist">
                                    <li><img src="./asset/img/iconSetting.png" alt="" class="iconNav">Paramètres</li>
                                </a>
                            <?php } ?>

                        </ul>
                    </div>
                    <hr>
                    <div class="chat">
                        <p>discutions</p>
                    </div>
                </div>
            </div>
            <div class="mainAjax">
            <?= $template ?>
            </div>
        </div>
    </main>
    <footer class="bg-body-secondary footer mt-auto p-3">
        <form class="d-flex" role="search">
            <input name="page" value="search" type="hidden">
            <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <section class="container-fluid text-center">
            &copy; DWWM CCI LYON
        </section>
    </footer>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>