<h1>Users</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Roles</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($data['selectUsers'] as $user) : ?>
    <tr>
      <th scope="row"><?= $user['id'] ?></th>
      <td><?= $user['name'] ?></td>
      <td><?= $user['email'] ?></td>
      <td><?= $user['roles'] ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
