
<h1>Articles</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Source</th>
      <th scope="col">Auteur</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($data['selectPicture'] as $picture) : ?>
    <tr>
      <th scope="row"><?= $picture['id'] ?></th>
      <td><?= $picture['title'] ?></td>
      <td><?= $picture['description'] ?></td>
      <td><?= $picture['src'] ?></td>
      <td><?= $picture['author'] ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>